#!/bin/sh

[ "$(printf %.1s "$0")" = / ] && SCRIPT_PATH="$0" || SCRIPT_PATH="$PWD/$0"
SCRIPT_DIR=${SCRIPT_PATH%/*}/

alias echo="echo [POS-IMP]"

CMD=$1
case $CMD in

    build | release | clean )
        for FOLDER in "$SCRIPT_DIR"/*/; do
            [ -e "$FOLDER/.projskip" ] && continue
            [ ! -x "$FOLDER/project" ] && continue
            "$FOLDER/project" "$@"
        done
    ;;

    test )
        "$SCRIPT_DIR/tests/test"
    ;;

    * )
        echo "$0 { build | release | clean }"
    ;;

esac
