#!/bin/sh

# Framework functions

T_INIT () {
    _T_TESTING_FAILED=
}

T_TESTCASE () {
    _T_TESTCASE_NAME="$@"
    _T_TESTCASE_FAILED=
}

T_FAIL () {
    _T_TESTING_FAILED=.
    _T_TESTCASE_FAILED=.
}

# Queries

T_HAS_TESTCASE_PASSED () { [ ! "$_T_TESTCASE_FAILED" ] ;}
T_HAS_TESTCASE_FAILED () { [   "$_T_TESTCASE_FAILED" ] ;}
T_HAS_ALL_PASSED () { [ ! "$_T_TESTING_FAILED" ] ;}
T_HAS_ANY_FAILED () { [   "$_T_TESTING_FAILED" ] ;}

# Testing decorators

SILENCE () { "$@" > /dev/null ;}

ASSERT_SILENT () {
    :
}

ASSERT_TRUE () {
    "$@"
    ERRVAL=$?
    [ 0 -ne "$ERRVAL" ] && T_FAIL
    return "$ERRVAL"
}

ASSERT_FALSE () {
    "$@"
    ERRVAL=$?
    [ 0 -eq "$ERRVAL" ] && T_FAIL
    return "$ERRVAL"
}
